### ISSUE TITLE
SpreadsheetQuery object source missing?

### ISSUE THREAD

**Issue by oceanborn2** [MetadataConsulting/spreadsheet-builder#13]
Hello, I gave a try to the SpreadSheet builder and I find it very interesting.

I stumbled upon a problem with the following line of code in the example:

> SpreadsheetQuery query = PoiSpreadsheetQuery.FACTORY.forFile(file)      

The source for these two classes seems to be missing    (I did a grep over all the source to make sure it was not defined embedded within another class).

The only references are in the Asciidoc documentation.

I managed to make it working by using the following code as a replacement:

> SpreadsheetCriteria ssc = PoiSpreadsheetCriteria.FACTORY.forFile(file)

It may also be an issue of the example not being updated to the latest version of the API?

**Comment by musketyr** [comment]
yes, this is definitely the problem. thanks for pointing this out, I'll fix it tomorrow.

**Comment by musketyr** [comment]
should be fixed

**Comment by oceanborn2** [comment]
Thanks. That was quick ☺ Have a good day. 

Pascal 

-----Original Message-----
