### ISSUE TITLE
"Unable to load extension class" warning message with version 0.3.1

### ISSUE THREAD

**Issue by cwchien** [MetadataConsulting/spreadsheet-builder#14]
First, thanks a lot for this awesome library for handling speadsheets. :)

The following warning message appeared after upgrade to **spreadsheet-builder-poi 0.3.1**

```
Oct 21, 2016 2:35:47 PM org.codehaus.groovy.runtime.m12n.MetaInfExtensionModule newModule
WARNING: Module [spreadsheet-builder-api] - Unable to load extension class 
[org.modelcatalogue.spreadsheet.builder.api.extensions.SpreadsheetBuilderModule]
```
Switch back to **0.3.0**, it disappeared.

--
OS: Ubuntu Linux 64bit
Java: OpenJDK 1.8.0 u102
Groovy: 2.4.7

**Comment by musketyr** [comment]
You're welcome :-)

Please, try version `0.3.1.1`. That one should have the descriptor fixed.

**Comment by cwchien** [comment]
It fixed. Thanks a lot. ;)
