### ISSUE TITLE
Zero is displayed as blank cell

### ISSUE THREAD

**Issue by atapin** [MetadataConsulting/spreadsheet-builder#16]
in `PoiCellDefinition`, there is:
```
   @Override
    void value(Object value) {
        if (!value) {
            xssfCell.setCellType(Cell.CELL_TYPE_BLANK)
            return
        }
        ....
    }
```

Looks like `0` falls into the first check.
I think, the correct way is to compare `value` to `null` explicitly.

**Comment by musketyr** [comment]
well spotted! will be fixed soon!

**Comment by atapin** [comment]
I've created a PR, if you don't mind

**Comment by musketyr** [comment]
@atapin brilliant! many thanks! I've just left there one comment

**Comment by atapin** [comment]
@musketyr can't see one. Have you commented on the PR?

**Comment by musketyr** [comment]
@atapin yes. see https://github.com/MetadataConsulting/spreadsheet-builder/pull/17/files/004e5f9800eb04d49d42a5e1aa0e0ba6e9a2d855

**Comment by atapin** [comment]
@musketyr hm, I don't see anything by some reason. Probably, you haven't submit it or clicked 'Start review'

**Comment by musketyr** [comment]
@atapin  that's probably the case. I'm sorry, this is first time I'm using the new reviews. check it now, please

**Comment by atapin** [comment]
@musketyr thanks for the comment. I've replied
