### ISSUE TITLE
Hide/unhide sheets

### ISSUE THREAD

**Issue by atapin** [MetadataConsulting/spreadsheet-builder#19]
There is an ability to hide/unhide sheets in Excel. It would be great to have it in the API, if POI allowed.
![image](https://cloud.githubusercontent.com/assets/1181403/23936585/cf09f16a-0974-11e7-980d-52cde581abf0.png)

UPD: [POI methods](https://poi.apache.org/apidocs/org/apache/poi/ss/usermodel/Workbook.html#getSheetVisibility(int))

**Comment by musketyr** [comment]
sure, there is an not very friendly API in POI for it, so let's do it

**Comment by atapin** [comment]
@musketyr seems like this can be closed according to 35c0eb

**Comment by musketyr** [comment]
I'm waiting for one more feature to add to 1.0 but yes, it done already.
