### ISSUE TITLE
width in sensible units

### ISSUE THREAD

**Issue by musketyr** [MetadataConsulting/spreadsheet-builder#2]
we should be able to set the width in `cm` and `inches`

**Comment by atapin** [comment]
This feature would be great. Do you already have any ideas how to build this in?

Ideally, writing

 ```
cell {
    width 10.cm
}
```
would be cool, but we need to have expansions for `Integer` on classpath by the moment of writing.

Another option:

```
cell {
    width cm(10)
}
```

where `cm()` is a static cm to points converter.

**Comment by musketyr** [comment]
Not really as the width varies with the font size as far as I know.

**Comment by musketyr** [comment]
this might be helpful: http://stackoverflow.com/a/35489052/227419

From the two proposed implementation I would go for the second one as I'm trying to keep the API statically compilable. Yet `cm` should not be static method but method of the `Cell` interface.

**Comment by musketyr** [comment]
also it looks like width and height needs to be handled differently so method `cm` should return some wrapper type e.g. `MetricDimention` instead of just `Integer` value. Then `width` and `height` requires to have two more method accepting this `MetricDimention` objects and parsing them accordingly.

**Comment by atapin** [comment]
@musketyr I'll take a look and try to help

**Comment by musketyr** [comment]
That would be great!

**Comment by musketyr** [comment]
fixed in 99aad3a

**Comment by musketyr** [comment]
I'm sorry, I got to this tonight as well. I have couple of more enhancements and then I'll release the new version
